### PR TITLE
Revert to call_tir with class prefix

### PR DESCRIPTION
**Pull request by sudeepag**
Per feedback on https://github.com/mlc-ai/notebooks/pull/10, reverting to `call_tir` with a `cls` prefix in the invocation.

[Preview](https://github.com/mlc-ai/notebooks/blob/9a12b30510bbc8b9f35bf285f83b58c2ce9f1a33/4_Build_End_to_End_Model.ipynb)

### CODE REVIEW

**Comment by sudeepag** [comment]
@tqchen This works correctly when using `call_tir` on primitive functions defined within the class, but I get an error when using it with registered runtime functions, for example:

```python
@tvm.script.ir_module
class MyModuleWithExternCall:
    @R.function
    def main(x: R.Tensor((1, 784), "float32"), 
             w0: R.Tensor((128, 784), "float32"), 
             b0: R.Tensor((128,), "float32"), 
             w1: R.Tensor((10, 128), "float32"), 
             b1: R.Tensor((10,), "float32")):
        # block 0
        with R.dataflow():
            lv0 = R.call_tir("env.linear", (x, w0, b0), out_sinfo=R.Tensor((1, 128), dtype="float32"))
            lv1 = R.call_tir("env.relu", (lv0,), out_sinfo=R.Tensor((1, 128), dtype="float32"))
            out = R.call_tir("env.linear", (lv1, w1, b1), out_sinfo=R.Tensor((1, 10), dtype="float32"))
            R.output(out)
        return out
```

```
error:   Check failed: type_code_ == kTVMObjectHandle (11 vs. 8) : expected Object but got str
 --> [/tmp/ipykernel_261925/1336559420.py:11:19](https://file+.vscode-resource.vscode-cdn.net/tmp/ipykernel_261925/1336559420.py:11:19)
    |  
 11 |              lv0 = R.call_tir("env.linear", (x, w0, b0), out_sinfo=R.Tensor((1, 128), dtype="float32"))
```

Is there a different syntax for using `call_tir` with registered functions?

**Comment by tqchen** [comment]
for runtime functions, we should indeed use call_dps_packed

**Comment by sudeepag** [comment]
@tqchen Thanks, ready for review.

[Preview](https://github.com/mlc-ai/notebooks/blob/9a12b30510bbc8b9f35bf285f83b58c2ce9f1a33/4_Build_End_to_End_Model.ipynb)

**Comment by tqchen** [comment]
Thanks @sudeepag

**Pull request merged**
