### PR TITLE
Update usage of call_tir

### PR DESCRIPTION
**Pull request by sudeepag**
Running the notebook currently throws the following error:

```
error: Undefined variable: linear0
 --> /tmp/ipykernel_195051/3764025160.py:58:30
    |  
 58 |              lv0 = R.call_tir(linear0, (x, w0, b0), (1, 128), dtype="float32")
    |                       
```

Based on the course [notes](https://mlc.ai/chapter_end_to_end/index.html), it appears that the API may have been changed to `call_dps_packed`, so updating the notebook to reflect the change.

cc @tqchen @jinhongyii @MasterJH5574 

[Preview](https://github.com/mlc-ai/notebooks/blob/1c91ccf6afc51ef3033f971e16208ecbdbbc5b21/4_Build_End_to_End_Model.ipynb)

### CODE REVIEW

**Comment by sudeepag** [comment]
Addresses https://github.com/mlc-ai/notebooks/issues/8.

**Comment by tqchen** [comment]
sorry i merged pre-maturely. actually call_tir is right, just that we need to have a cls prefix, 
```python

@tvm.script.ir_module
class MyModule:
   @T.prim_func
   def linear():


   @R.function
   def main(x)
         cls = MyModule
         R.call_tir(cls.linear, ...)

```

**Comment by tqchen** [comment]
@sudeepag can you send an update

**Comment by sudeepag** [comment]
@tqchen Thanks for clarifying. Yes, I will revert to `call_tir` with the prefix.

**Pull request merged**
